Squashed commit of the following:
commit 9d4b82a5b9a5e4d501deb43ec06834cf6e753aac
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Sun Apr 13 21:56:16 2025 +0300

    Restart with packages

    npx expo install @react-navigation/native @react-navigation/native-stack @react-navigation/bottom-tabs @react-navigation/drawer react-native-screens react-native-safe-area-context react-native-gesture-handler react-native-reanimated

commit 85aa06ac70740cf42669337aa249df1ee5b3d480
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Sun Apr 13 21:33:22 2025 +0300

    JUST KILLED MY PROJ)

    Error: [Reanimated] Babel plugin exception: TypeError: Cannot set properties of undefined (setting 'workletNumber')

commit c73e799d3c51afd7207646f548537cdebd0bacad
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Sun Apr 13 20:12:04 2025 +0300

    Finally it works with tabs

commit 1842e24c2a82d07cad297c82b7c67037ee5fb492
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Sun Apr 13 16:27:08 2025 +0300

    Redacted details

commit 9c61306aee33e56794b0ea75a8eb8a9fa7f4aa0a
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 20:50:26 2025 +0300

    I've got only 3 errors, yappyyyyyy

commit ef367129ec932c1b8999c7b591d8d56d6d56860f
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 20:28:08 2025 +0300

    Works exept details

commit 8017670e8e8b285312433874e09619b11486eccc
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 20:02:30 2025 +0300

    Trying to make tab and Stack props

commit 22e634802634d6e8ed18cb0016ffa8a1a5b1ff17
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 19:39:55 2025 +0300

    Added header

    npx expo install @react-navigation/bottom-tabs

    Got problems with tab.navigetor

commit f4934fe82b6b87c65ded3d78c9d94842fd8cb993
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 18:12:00 2025 +0300

    Created RootStackParamList

commit 4dde0d15dc514869f72c53f3249c8b907ec88288
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 18:06:35 2025 +0300

    Added screens

    Got error with exporting RootStackParamList

commit ae1b422dcc6c1ac9b1fcc1e29255c17badbb4e53
Author: Daniyl <124207779+DannMZ@users.noreply.github.com>
Date:   Fri Apr 11 17:54:53 2025 +0300

    Start

    create-expo-app --template
    Blank (TypeScript)

    And
    npx expo install @react-navigation/native @react-navigation/native-stack react-native-screens react-native-safe-area-context